application/controllers/fonte/helios/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url, include

import url_names as names
import views

urlpatterns = [
  url(r'^autologin$', views.admin_autologin),
  url(r'^testcookie$', views.test_cookie, name=names.COOKIE_TEST),
  url(r'^testcookie_2$', views.test_cookie_2, name=names.COOKIE_TEST_2),
  url(r'^nocookies$', views.nocookies, name=names.COOKIE_NO),
  url(r'^stats/', include('helios.stats_urls')),

  # election shortcut by shortname
  url(r'^e/(?P<election_short_name>[^/]+)$', views.election_shortcut, name=names.ELECTION_SHORTCUT),
  url(r'^e/(?P<election_short_name>[^/]+)/vote$', views.election_vote_shortcut, name=names.ELECTION_SHORTCUT_VOTE),

  # vote shortcut
  url(r'^v/(?P<vote_tinyhash>[^/]+)$', views.castvote_shortcut, name=names.CAST_VOTE_SHORTCUT),
  
  # trustee login
  url(r'^t/(?P<election_short_name>[^/]+)/(?P<trustee_email>[^/]+)/(?P<trustee_secret>[^/]+)$', views.trustee_login,
      name=names.TRUSTEE_LOGIN),
  
  # election
  url(r'^elections/params$', views.election_params, name=names.ELECTIONS_PARAMS),
  url(r'^elections/verifier$', views.election_verifier, name=names.ELECTIONS_VERIFIER),
  url(r'^elections/single_ballot_verifier$', views.election_single_ballot_verifier, name=names.ELECTIONS_VERIFIER_SINGLE_BALLOT),
  url(r'^elections/new$', views.election_new, name=names.ELECTIONS_NEW),
  url(r'^elections/administered$', views.elections_administered, name=names.ELECTIONS_ADMINISTERED),
  url(r'^elections/voted$', views.elections_voted, name=names.ELECTIONS_VOTED),
  
  url(r'^elections/(?P<election_uuid>[^/]+)', include('helios.election_urls')),

  url(r'^heliosinstitution/', include('heliosinstitution.urls')),
]

application/controllers/fonte/helios/forms.py
"""
Forms for Helios
"""

from django import forms
from models import Election
from widgets import SplitSelectDateTimeWidget
from fields import SplitDateTimeField
from django.conf import settings
from django.utils.translation import ugettext_lazy as _


class ElectionForm(forms.Form):
  short_name = forms.SlugField(max_length=40, label=_("Short name"),
    help_text=_('no spaces, will be part of the URL for your election, e.g. my-club-2010'))
  name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'size':60}),
    label=_("Name"), help_text=_('the pretty name for your election, e.g. My Club 2010 Election. Maximum of 250 characters.'))
  description = forms.CharField(max_length=4000, label=_("Description"),
    help_text=_("Maximum of 4000 characters. You can use the HTML tags: <p>, <h4>, <h5>, <h3>, <h2>, <br>, <u>."),
    widget=forms.Textarea(attrs={'wrap': 'soft', 'class': 'form-control'}), required=False)
  election_type = forms.ChoiceField(label=_("Type"), choices = Election.ELECTION_TYPES,
    widget=forms.HiddenInput(), initial=Election.ELECTION_TYPES[0][0], required=False)
  use_voter_aliases = forms.BooleanField(required=False, initial=True,
    label=_("Use voter aliases"), help_text=_('If selected, voter identities will be replaced with aliases, e.g. "V12", in the ballot tracking center'))
  use_advanced_audit_features = forms.BooleanField(required=False, initial=False,
    label = _("Use advanced audit features"),
    help_text=_('disable this only if you want a simple election with reduced security but a simpler user interface'))
  randomize_answer_order = forms.BooleanField(required=False, initial=False,
    label=_("Randomize answer order"), help_text=_('enable this if you want the answers to questions to appear in random order for each voter'))
  private_p = forms.BooleanField(required=False, initial=True, label=_("Private?"),
          help_text=_('A private election is only visible to registered voters.'))
  help_email = forms.CharField(required=False, initial="", label=_("Help Email Address"),
    help_text=_('An email address voters should contact if they need help.'),
    widget=forms.TextInput(attrs={'size':60}))

  if settings.ALLOW_ELECTION_INFO_URL:
    election_info_url = forms.CharField(required=False, initial="", label=_("Election Info Download URL"), help_text=_("the URL of a PDF document that contains extra election information, e.g. candidate bios and statements"))

    # times
  voting_starts_at = forms.DateTimeField(label = _("Voting starts at"),
    help_text = _('UTC date and time when voting begins'),
    input_formats=['%d/%m/%Y %H:%M'],
    widget=forms.DateTimeInput(format='%d/%m/%Y %H:%M'),
    required = False)
  voting_ends_at = forms.DateTimeField(help_text = _("UTC date and time when voting ends"),
    label = _("Voting ends at"),
    input_formats=['%d/%m/%Y %H:%M'],
    widget=forms.DateTimeInput(format='%d/%m/%Y %H:%M'),
    required=False)

  def clean(self):
    cleaned_data = super(ElectionForm, self).clean()
    election_type = cleaned_data.get("election_type")
    if election_type == '':
      cleaned_data['election_type'] = self.fields['election_type'].initial
    return cleaned_data


class ElectionTimesForm(forms.Form):
  # times
  voting_starts_at = forms.DateTimeField(label = _("Voting starts at"),
    help_text = _('UTC date and time when voting begins'),
    input_formats=['%d/%m/%Y %H:%M'],
    widget=forms.DateTimeInput(format='%d/%m/%Y %H:%M'),

    )
  voting_ends_at = forms.DateTimeField(help_text = _('UTC date and time when voting ends'),
    label = _("Voting ends at"),
    input_formats=['%d/%m/%Y %H:%M'],
    widget=forms.DateTimeInput(format='%d/%m/%Y %H:%M'))

class ElectionTimeExtensionForm(forms.Form):
  voting_extended_until = forms.DateTimeField(help_text = _("UTC date and time voting extended to"),
    label = _("Voting extended until"),
    input_formats=['%d/%m/%Y %H:%M'],
    widget=forms.DateTimeInput(format='%d/%m/%Y %H:%M'),
    required=False)

class EmailVotersForm(forms.Form):
  subject = forms.CharField(max_length=80, required=True)
  body = forms.CharField(max_length=4000, widget=forms.Textarea)
  send_to = forms.ChoiceField(label=_("Send To"), initial="all", choices= [('all', _('all voters')), ('voted', _('voters who have cast a ballot')), ('not-voted', _('voters who have not yet cast a ballot'))])


class TallyNotificationEmailForm(forms.Form):
  subject = forms.CharField(max_length=80)
  body = forms.CharField(max_length=2000, widget=forms.Textarea, required=False)
  send_to = forms.ChoiceField(label=_("Send To"), choices= [
    ('all', _('all voters')),
      ('voted', _('only voters who cast a ballot')),
      ('none', _('no one -- are you sure about this?'))])

class VoterPasswordForm(forms.Form):
  voter_id = forms.CharField(max_length=50, label=_("Voter ID"))
  password = forms.CharField(widget=forms.PasswordInput(), max_length=100)

application/controllers/fonte/helios/templates/_castconfirm_docast.html
{% load i18n %}
{% if election.voting_has_started %}
  {% if not election.voting_has_stopped %}

<div id="cast_form">
<form id="cast_confirm_form" method="post" action="" onsubmit="show_waiting()">
    <input type="hidden" name="csrf_token" value="{{csrf_token}}" />

{% if status_update_label %}
<div class="round" style="background: #eee; padding: 10px; border: 1px dashed #888;">
<input type="checkbox" name="status_update" value="1" checked /> {{status_update_label}}<br />
<blockquote style="font-size: 1.3em;">
"{{status_update_message}}"
</blockquote>
<input type="hidden" name="status_update_message" value="{{status_update_message}}" />
</div>
<br />
{% endif %}
{% trans "You are logged in as " %} <u>{{voter|safe}}</u><br /><br />

    <button class="btn btn-primary" type="submit" >{% trans "CAST this ballot" %}</button>
    <button class="btn btn-danger" type="button" onclick="document.location='/auth/logout';">{% trans "cancel" %}</button><br />
</form>
<p>
    <span style="font-size:0.8em;"><br />{% trans "You can cast as many ballots as you want.<em><br>Only the last one counts</em>." %}</span>
</p>
<p>
    <span style="font-size:0.9em;"><strong>{% blocktrans %}If you cancel now, your ballot will <em>NOT</em> be recorded.<br />
    You can start the voting process over again, of course.{% endblocktrans %}</strong></span>
</p>

<!-- for now, for CSRF protection, no auto-submit just yet (benadida) -->
<!-- <script>$('#cast_confirm_form').submit()</script> -->

</div>
  {% else %}
<p>
  {% trans "voting has stopped, sorry." %}
</p>
  {% endif %}
{% else %}
<p>
  {% trans "voting has not yet begun, sorry." %}
</p>

{% endif %}

{% if not election.voting_has_started or election.voting_has_stopped %}
    <p>
        {% trans "Visit"  %}  <a href="{{ election.url }}"> {{election.name}} </a> {% trans "for more info." %}
    </p>
{% endif %}

application/controllers/fonte/helios/templates/_castconfirm_password.html
{% load i18n %}
{% trans "Please provide the voter ID and password you received by email." %}<br /><br />
<div class="col-md-4">
<form method="post" action="{% url "election@password-voter-login" election.uuid %}" onsubmit="show_waiting()" class="form-horizontal" role="form">
<input type="hidden" name="csrf_token" value="{{csrf_token}}" />
<input type="hidden" name="return_url" value="{{return_url}}" />
<input type="hidden" name="cast_ballot" value="{{cast_ballot}}" />
  <div class="form-group">
    <label for="exampleInputEmail1">{% trans "Voter ID" %}</label>
    <input type="text" class="form-control" id="voter_id" name="voter_id" placeholder="{% trans "Voter ID" %}">
  </div>
	<div class="form-group">
    <label for="password">{% trans "Password" %}</label>
    <input type="password" class="form-control" id="id_password" name="password" placeholder="{% trans "Password" %}">
  	</div>

{% if bad_voter_login %}
<p style="color: red;">
{% trans "bad voter ID or password, please try again." %}
</p>
{% endif %}
<div class="form-group">
{% if cast_ballot == "1" %}
<button type="submit" class="btn btn-primary">{% trans "Confirm" %}</button>
{% else %}
<button type="submit" class="btn btn-primary">{% trans "Login" %}</button>
{% endif %}
</div>
</div>
</form>

application/controllers/fonte/helios/templates/cast_done.html
{% extends TEMPLATE_BASENONAV %}
{% load i18n %}
{% block title %}Voto depositado!{% endblock %}

{% block content %}
<h2>{{election.name}}</h2>
<br>
<h4>
{% blocktrans %}
    Congratulations, your vote has been <b><u>successfully cast</u></b>!
{% endblocktrans %}
</h4>
<br>

<div class="alert alert-info" role="alert">
<p>
{% trans "Your smart ballot tracker is:" %}
  <tt style="font-size: 10pt;width: 10em; word-wrap: break-word; font-weight: bold; ">  {{vote_hash}}</tt>
</p>
</div>
</p>
<br><br>
{% if logout %}
<p><span>{% trans "For your safety, we have logged you out." %}</span></p>
<iframe width="0" height="0" border="0" frameborder="0" src="{% url "auth@logout" %}">
</iframe>
{% endif %}

{% endblock %}

application/controllers/fonte/helios/templates/castvote.html
{% extends TEMPLATE_BASE %}
{% load i18n %}
{% block title %}{{cast_vote.vote_tinyhash}} &mdash; {{election.name}}{% endblock %}
{% block content %}
<h2 class="title">{% trans "Cast Vote" %} {{cast_vote.vote_tinyhash}}</h2>
{% trans "cast in" %} <a href="{% url "election@view" election.uuid %}">{{election.name}}</a><br />
{% trans "Fingerprint: " %}<tt>{{cast_vote.vote_hash}}</tt><br />
by <b><u>
{% if the_voter.alias %}
{{the_voter.alias}}
{% else %}
{{the_voter.name}}
{% endif %}
</u></b>
<br /><br />

{% endblock %}

application/controllers/fonte/helios/templates/cryptobase.html
{% extends TEMPLATE_BASE %}
{% load staticfiles %}
{% block js %}
<script language="javascript" src="{% static "js/underscore-min.js" %}"></script>
<script language="javascript" src="{% static "js/jquery-jtemplates.js" %}"></script>
<script language="javascript" src="{% static "js/jquery.json.min.js" %}"></script>

<script language="javascript" src="{% static "js/jscrypto/jsbn.js" %}"></script>
<script language="javascript" src="{% static "js/jscrypto/jsbn2.js" %}"></script>
<script language="javascript" src="{% static "js/jscrypto/sjcl.js" %}"></script>

<script language="javascript">
  // required for jscrypto library
  var JSCRYPTO_HOME = "{% static "js/jscrypto" %}";
</script>

<script language="javascript" src="{% static "js/jscrypto/class.js" %}"></script>  
<script language="javascript" src="{% static "js/jscrypto/bigint.js" %}"></script>
<script language="javascript" src="{% static "js/jscrypto/random.js" %}"></script>
<script language="javascript" src="{% static "js/jscrypto/elgamal.js" %}"></script>
<script language="javascript" src="{% static "js/jscrypto/sha1.js" %}"></script>
<script language="javascript" src="{% static "js/jscrypto/sha2.js" %}"></script>
<script language="javascript" src="{% static "js/jscrypto/helios.js" %}"></script>
{% endblock %}

application/controllers/fonte/helios/templates/election_new_2.html
{% extends "helios/templates/cryptobase.html" %}
{% load i18n %}
{% block content %}
<script language="javascript">

var SECRET_KEY;

function before_create() {
{% ifequal election_type "one" %}
    return confirm('Have you made sure to copy the private key to a safe place?\n\nOnce you click OK, Helios will not be able to recover the secret key without your help!');
{% else %}
    return true;
{% endifequal %}
}

function generate_keypair() {
    ELGAMAL_PARAMS = ElGamal.Params.fromJSONObject({{eg_params_json|safe}});

    $('#generate_button').hide();
    
    try {
        SECRET_KEY = ELGAMAL_PARAMS.generate();
    } catch (e) {
        alert(e);
    }

    $('#pk').val(jQuery.toJSON(SECRET_KEY.pk));
    
{% ifequal election_type "one" %}
    $('#sk_textarea').val(jQuery.toJSON(SECRET_KEY));
    $('#sk_form').show();
{% else %}
{% ifequal election_type "helios" %}
    $('#sk').val(jQuery.toJSON(SECRET_KEY));
{% endifequal %}
{% endifequal %}

    $('#submit').show();
}

$(document).ready(function() {
{% ifnotequal election_type "multiple" %}
    $('#submit').hide();
{% endifnotequal %}
    $('#sk_form').hide();
});
</script>

  <h2 class="title">{% trans "Create a New Election:" %} {{name}}</h2>
{% ifequal election_type "helios" %}
  {% blocktrans %}
  <b>An election managed by Helios</b>.
  {% endblocktrans %}
{% else %}
{% ifequal election_type "one" %}
  {% blocktrans %}
  <b>An election managed by you, the single administrator</b>.
  {% endblocktrans %}
{% else %}
  {% blocktrans %}
<b>An election managed by multiple trustees</b>.
  {% endblocktrans %}
{% endifequal %}
{% endifequal %}
  <form class="prettyform" action="{% url "elections@new_3" %}" method="POST" id="create_election_form" onsubmit="return before_create();">
      <input type="hidden" name="csrf_token" value="{{csrf_token}}" />
      <input type="hidden" name="name" value="{{name}}" />
      <input type="hidden" name="public_key" id="pk" value="" />
      <input type="hidden" name="private_key" id="sk" value="" /><br />

{% ifnotequal election_type "multiple" %}
  <label for="generate_key">&nbsp;</label><button onclick="generate_keypair(); return false;" id="generate_button">
  {% blocktrans %}
   Generate Election Keys
  {% endblocktrans %}
    </button>
{% else %}
<div id="trustees">
<h3> {% blocktrans %}
  Trustees (up to 5)
{% endblocktrans %}
 </h3>

<label for="">&nbsp;</label> <input type="text" name="trustee" /><br />
<label for="">&nbsp;</label> <input type="text" name="trustee" /><br />
<label for="">&nbsp;</label> <input type="text" name="trustee" /><br />
<label for="">&nbsp;</label> <input type="text" name="trustee" /><br />
<label for="">&nbsp;</label> <input type="text" name="trustee" /><br />
</div>
{% endifnotequal %}
<br /><br />
<label for="">&nbsp;</label>  <input type="submit" value="{% trans "create" %}" id="submit" />
  </form>
  <br /><br />
{% ifequal election_type "one" %}
  <form style="padding-left: 200px;" id="sk_form" onsubmit="return false;">
      <input type="hidden" name="csrf_token" value="{{csrf_token}}" />
      {% blocktrans %}
      Your Election's Secret Key:<br />
      {% endblocktrans %}
      <label for="">&nbsp;</label>
      <textarea id="sk_textarea" cols="60" rows="5">
      </textarea><br />
      {% blocktrans %}
      (You need to copy and paste this key and keep it safe,<br />
      otherwise you won't be able to tally your election.)
      {% endblocktrans %}
  </form>
{% endifequal %}
{% endblock %}

application/controllers/fonte/helios/templates/list_trustees.html
{% extends "helios/templates/cryptobase.html" %}
{% load i18n %}
{% block title %}{% trans "Trustees for" %} {{election.name}}{% endblock %}

{% block content %}
  <h3 class="title">{% trans "Trustees" %} <span style="font-size:0.7em;">[<a href="{% url "election@view" election.uuid %}">{% trans "back to election" %}</a>]</span></h3>
  <h3 class="title">{{election.name}}</h3>
<p>
<br>
{% if admin_p %}
{% blocktrans %}
    Trustees are responsible for decrypting the election result.<br />
    Each trustee generates a keypair and submits the public portion to Helios.<br />
    When it's time to decrypt, each trustee needs to provide his secret key.
{% endblocktrans %}
</p>

{% if not election.frozen_at %}

<p>
{% if election.has_helios_trustee %}
{% blocktrans %}
  Helios is automatically your first trustee and will handle its keypair generation and decryption automatically.<br />
  You may add additional trustees if you want, and you can even remove the Helios trustee.<br />
  However, we recommend you do this only if you have a solid understanding of the trustee's role.
{% endblocktrans %}
{% endif %}
</p>


<p>
     <a class="btn btn-primary" id="add_trustee" href="{% url "election@trustees@new" election.uuid %}">{% trans "add a trustee" %}</a>
</p>
{% if not election.has_helios_trustee %}
<p>
    <a href="{% url "election@trustees@add-helios" election.uuid %}">{% trans "add Helios as a trustee" %}</a>
</p>
{% endif %}

{% endif %}

{% else %}

{% trans "Below are listed the trustees for this election." %}
{% endif %}

{% if not trustees|length %}

{% else %}
<br><br>
<table class="table table-striped">
  <thead>
    <tr>
      <th>{% trans "Trustee" %}</th>
      <th>{% trans "Public Key Fingerprint:" %}</th>
      <th></th>
      <th></th>
   </tr>

  </thead>
  <tbody>
{% for t in trustees %}
  <tr>
  <td>#{{forloop.counter}}: {{t.name}}</td>
  <td>

  {% if t.public_key_hash %}
    <strong>{{t.public_key_hash}}</strong>
  {% else %}
  {% trans "No public key uploaded yet." %}
  {% endif %}

  </td>
  <td>
  {% if election.encrypted_tally %}
  {% if t.decryption_factors %}
  <span title="{% trans "tally recorded for this trustee." %}" class="glyphicon glyphicon-ok-sign"></span>
  {% else %}
  <span title="{% trans "waiting for this trustee's tally" %}" class="glyphicon glyphicon-info-sign"></span>
  {% endif %}
  {% endif %}
  </td>
  <td>

  {% if admin_p %}
    {% if t.secret_key %}
      {% if not election.frozen_at %}
          <a class="remove_helios_as_trustee" class="glyphicon glyphicon-remove" href="{% url "election@trustees@delete" election.uuid %}?uuid={{t.uuid}}">
           <i title="{% trans "Remove trustee" %}" class="glyphicon glyphicon-remove"></i></a>
      {% endif %}
    {% else %}
      {{t.email}}
      {% if not election.frozen_at %}
              <a class="remove_trustee" class="glyphicon glyphicon-remove" href="{% url "election@trustees@delete" election.uuid %}?uuid={{t.uuid}}"><i title="{% trans "Remove trustee" %}" class="glyphicon glyphicon-remove"></i></a>
      {% endif %}
               <a title="{% trans "send login" %}" class="glyphicon glyphicon-envelope send_trustee_url" href="{% url "election@trustee@send-url" election.uuid t.uuid %}"></a>
    {% endif %}
  {% endif %}
  </td>
  </tr>
{% endfor %}
</tbody>
</table>
{% endif %}

{% endblock %}

application/controllers/fonte/helios/templates/stats.html
{% extends TEMPLATE_BASE %}
{% load i18n %}
{% block title %}{% trans "Admin" %}{% endblock %}
{% block content %}
<h3>{% trans "Statistics" %}</h3>

<ul>
<li> <a href="{% url "stats@elections" %}">{% trans "elections" %}</a></li>
<li> <a href="{% url "stats@recent-votes" %}">{% trans "recent votes" %}</a></li>
<li> <a href="{% url "stats@elections-problems" %}">{% trans "recent problem elections" %}</a></li>
<li> <a href="{% url "stats@admin-actions" %}">{% trans "Admin actions" %}</a></li>
</ul>

<p><b>{{num_votes_in_queue}}</b> {% trans "votes in queue." %} {% if num_votes_in_queue %}[<a href="{% url "stats@force-queue" %}">{% trans "force it" %}</a>]{% endif %}</p>

{% endblock %}

application/controllers/fonte/helios/templates/stats_elections.html
{% extends TEMPLATE_BASE %}
{% load i18n %}
{% block title %}{% trans "Statistics" %}{% endblock %}
{% block content %}
<div class="col-md-12">
<h1>{% trans "Elections" %}</h1>

<p>
<form method="get" action="{% url "stats@elections" %}">
<b>{% trans "search" %}</b>: <input type="text" name="q" value="{{q}}"/>
<input class="small button" type="submit" value="{% trans "search" %}" /> <a class="small button" href="?">{%trans "clear search" %}</a>
</form>
</p>

<p>
{% if elections_page.has_previous %}
<a href="?page={{elections_page.previous_page_number}}&limit={{limit}}&q={{q|urlencode}}">{% trans "previous" %} {{limit}}</a> &nbsp;&nbsp;
{% endif %}

{% trans "Elections" %} {{elections_page.start_index}} - {{elections_page.end_index}} ({% trans "of" %} {{total_elections}})&nbsp;&nbsp;

{% if elections_page.has_next %}
<a href="?page={{elections_page.next_page_number}}&limit={{limit}}&q={{q|urlencode}}">next {{limit}}</a> &nbsp;&nbsp;
{% endif %}
	<table class="table table-striped">
	  <thead>
	    <tr>
	      <th>{% trans "Election" %}</th>
	      <th>{% trans "Admin" %}</th>
	      <th>{% trans "voters / cast votes" %}</th>
	   </tr>
	  </thead>
	  <tbody>
{% for election in elections %}
<tr>
<td><b><a href="{% url "election@view" election.uuid %}">{{election.name}}</a></b></td>
<td><a href="mailto:{{election.admin.info.email}}">{{election.admin.pretty_name}}</a> </td>
<td>{{election.num_voters}} / {{election.num_cast_votes}}</td>
</tr>
{% endfor %}
</tbody>
</table>
</div>
{% endblock %}

application/controllers/fonte/helios/templates/voters_email.html
{% extends TEMPLATE_BASE %}
{% load i18n %}
{% block title %}{% trans "Contact Voters for" %} {{election.name}}{% endblock %}
{% block content %}
<script>
var voter_id = null;
{% if voter %}
voter_id = '{{voter.voter_id}}';
{% endif %}
</script>
<div class="col-md-10">
  <h2 class="title">{% trans "Contact Voters" %} <span style="font-size:0.7em;">[<a href="{% url "election@view" election.uuid %}">{% trans "back to election" %}</a>]</span></h2>
  <h2 class="title">{{election.name}}</h2>

{% if voter %}  
  <p>

  {% trans "You are sending this email to a specific user:" %} <b>{{voter.name}} ({{voter.voter_id}})</b>

  </p>
{% endif %}
<br>

<h3>{% trans "Choose the email type you want to send:" %}</h3>
</div>
<div class="col-md-6">
<ul class="nav nav-pills nav-stacked">
{% for template_option in templates %}
{% if template_option.0 == template %}
<li class="active"><a href="?template={{template_option.1}}">{{template_option.1}}</a></li>
{% else %}
<li><a href="?template={{template_option.0}}&voter_id={{voter.voter_login_id}}">{{template_option.1}}</a></li>
{% endif %}
{% endfor %}
</ul>
</div>
<div class="col-md-10">
<pre style="margin:10px; border: 1px solid #888; padding:20px">
{% trans "Subject:" %} {{default_subject}}

{{default_body|safe}}
</pre>
</div>

<div class="col-md-10">
<p>
{% trans "You may tweak the subject and add a custom message using the form below." %}
</p>
  <form class="form" role="form" action="" method="POST" id="email_form">
    {{ email_form.non_field_errors }}
    <input type="hidden" name="csrf_token" value="{{csrf_token}}" />
    <input type="hidden" name="template" value="{{template}}" />
    <input type="hidden" name="voter_id" value="{{voter.voter_login_id}}" />
    <div class="form-group {% if email_form.subject.errors %}has-error{% endif %}">
    <label for="id_subject">{% if email_form.fields.subject.required %}*{% endif %}{% trans "Subject" %}</label>
    <input type="text" name="subject" class="form-control" id="id_subject" placeholder="{% trans "Subject" %}">

    {{email_form.subject.errors}}
    </div>
    <div class="form-group {% if email_form.body.errors %}has-error{% endif %}">
    <label for="body">{% trans "Body" %}</label><br>
    {% blocktrans %} What you type in here is what you get in the BODY tag on the template above {% endblocktrans %}
    <textarea name="body" class="form-control" id="id_body" rows="4" cols="50" placeholder="{% trans "Body" %}">
    </textarea>

    {{email_form.body.errors}}
    </div>

    <div id="send_to" class="form-group {% if email_form.send_to.errors %}has-error{% endif %}">
    <label for="send_to">{% trans "Send To" %}</label>
    {{email_form.send_to}}
    {{email_form.send_to.errors}}
    </div>


  <div class="form-group">
   <button type="submit" id="send_button" class="btn btn-primary">{% trans "Send" %}</button>
  </div>
  </form>
 </div>
  <div id="processing">
  </div>
  
  <div id="done" style="display:none;">
    {% trans "Done, go" %} <a href="{% url "election@view" election.uuid %}">{% trans "back to election" %}</a>.
  </div>

  <div id="error" style="display:none;">
  {% blocktrans %}
    Error emailing participants. Check server settings, make sure there's an SMTP server.
  {% endblocktrans %}
  </div>
<script language="javascript">
{% if voter %}
  $(document).ready(function() {
    $('div#send_to').hide();
  });
{% endif %}
</script>
{% endblock %}